name: Test-1_22

on:
  push:
    paths:
      - "**.go"
      - "**.md"
      - "**.yaml"
      - "**.mod"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use golang
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"
      # noinlineによるテスト実行
      # https://github.com/poteto-go/poteto/issues/169
      - name: Test
        run: go test ./... -cover -bench . -benchtime 100000x -gcflags=all=-l